### ISSUE TITLE
Please fix infinite loop

### ISSUE THREAD

**Issue by ndinhphi** [coderhaoxin/react-flatpickr#43]
Hi,
This is my code: 
<Flatpickr
                                onChange={v => {
                                  this.setState({
                                    task: update(this.state.task, {
                                      repeatEnd: { $set: new Date(v) }
                                    })
                                  });
                                }}
                                options={{
                                  minDate: this.state.task.startAt,
                                  maxDate: this.state.task.dueAt,
                                  enableTime: false,
                                  defaultDate: this.state.task.repeatEnd
                                }}
                              />

When defaultDate is null, I get infinite loop when I change value. But when defaultDate is not null, It works fine.
If I remove minDate, maxDate option, It works for defaultValue null.
Can you help me fix this. Thanks.
Sorry for my poor english.

**Comment by gitmurali** [comment]
This is very buggy I tried but it goes infinite and never stops for anyone.

**Comment by jacobmischka** [comment]
The prop `defaultValue` is the only one used by react-flatpickr, it passes it along to the underlying `<input />` element. The `defaultDate` attribute in the `options` object is merely passed along to flatpickr and isn't touched by react-flatpickr at all other than that.

That being said, I seem to be unable to reproduce this using those options. It seems like your problem is that your `setState` is causing the react component to rerender, which is causing the loop.

I don't see any infinite loops when using the following code. If I'm missing something please let me know what it is.

```js

import 'flatpickr/dist/themes/material_green.css'

import React, { Component } from 'react'
import { render } from 'react-dom'

import Flatpickr from '../'

class App extends Component {
  state = {
    defaultDateValue: null,
    onChange: (_, str) => {
      console.info(str)
    }
  }

  render() {
    return (
      <main>
        <Flatpickr
          onChange={v => {
            this.setState({defaultDateValue: v})
          }}
          value={this.state.defaultDateValue}
          options={{
            minDate: '2017-01-01',
            maxDate: '2018-01-01',
            defaultDate: null
          }} />
      </main>
    )
  }
}

window.init = () => {
  render(<App />, document.querySelector('#container'))
}
```

**Comment by rkmax** [comment]
I have this problem too when pass the `options.maxDate`, example how I'm using like follows

`<Flatpickr placeholder="Birthday" onChange={handleOnChange} options={maxDate: new Date()}/>`

When the whole app is rendered the first time I dont have problem (when user type the url and open) but when the user navigate from a diffent route, take a while (more than 30s) to able to change the route and then react prints on the console `Too much recursion`

**Comment by chongdog83** [comment]
I had the same issue and solved it by changing onChange to onClose... I feel like this library is somehow polling the value or something, which can easily create that infinite loop.

Also it returns an array with the date inside of it.  When I set the initial state to an empty array or empty string, it did that infinite loop.  When I set the initial date to a date string, it doesn't... but that feels wrong, why set the state to a string when it's going to return an array?  Also why set it in state to begin with if you are going to set the options to defaultDate: null?

All that being said, this is working for me:
(in this example I'm having the user tell me the start date and time of a party)
```
<Flatpickr
  data-enable-time
  id="start"
  name="start"
  options={{
    minDate: '2017-09-01',
    defaultDate: null,
    dateFormat: 'l m/d/Y at h:i K',
    altInputClass: 'form-conrol',
    minuteIncrement: '15'
  }}
  onClose={v => {this.setState({start: v})}}
  className="form-control"
  placeholder="Click here to select shift date and start time"
 />

**Comment by Phyks** [comment]
Same problem, using `onClose` does the trick, but is not fired when pressing backspace to clear the field :/

**Comment by ZeHiro** [comment]
The vug is here : https://github.com/coderhaoxin/react-flatpickr/blob/92ead47e3eaa3ddfbf03ee0cd755208961c2fd07/lib/index.js#L45

The component should check the value to be set is different from the current one.

**Comment by ZeHiro** [comment]
I'll propose a fix

**Comment by ZeHiro** [comment]
We had a bug in our code.

**Comment by jacobmischka** [comment]
I think should should be fixed in 3.6.1, but it's hard for me to tell because I still haven't been able to reproduce it. Please let me know either way, thanks!

**Comment by skattyadz** [comment]
I had this problem when creating a new `maxDate` object within the render function. Moving it to a const fixed it.

Bad:
```js
                  <Flatpickr
                    value={fromDate}
                    options={{ maxDate: new Date() }}
                    onChange={this.handleFromDateChange}
                  />
```

Good:
```js
const MAX_DATE = new Date();
...

                  <Flatpickr
                    value={fromDate}
                    options={{ maxDate: MAX_DATE }}
                    onChange={this.handleFromDateChange}
                  />
```

**Comment by rkmax** [comment]
@skattyadz  the problem is I need change the maxDate based on some business logic, so cannot be a constant on my code

**Comment by skattyadz** [comment]
Yea, I still don't see why it triggers a change and this is probably still
a bug

**Comment by jacobmischka** [comment]
Sorry, I have yet to be able to reproduce it. If someone can please provide a link to a repo or webpackbin or something that illustrates the issue I'll be happy to look into it, but I don't get any loops when trying any of the snippets posted in this issue.

**Comment by rkmax** [comment]
Today I did some testing https://www.webpackbin.com/bins/-L-SOX_Eo80IPC0Ojo-9, now I'm confused :/ it looks something with flatpickr library instead
